### By Normal method

In [1]:
from nltk.tokenize import word_tokenize
import pandas as pd
import numpy as np
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [2]:
sent_1 = "It is a good practice for us."
sent_2 = "It was also good to know about it."

In [3]:
t1 = word_tokenize(sent_1)
t2 = word_tokenize(sent_2)

In [4]:
# t3 =  t1 + t2
# t3

In [5]:
corpus = []
document1 = []
for i in t1:
    corpus.append(i.lower())
    document1.append(i.lower())

In [6]:
document2 = []
for i in t2:
    corpus.append(i.lower())
    document2.append(i.lower())

In [7]:
voca = set(corpus)
voca

{'.',
 'a',
 'about',
 'also',
 'for',
 'good',
 'is',
 'it',
 'know',
 'practice',
 'to',
 'us',
 'was'}

In [8]:
voca_lst = list(voca)
voca_lst

['good',
 'for',
 'about',
 'know',
 'us',
 '.',
 'a',
 'is',
 'it',
 'also',
 'practice',
 'was',
 'to']

In [9]:
sent_1_count = [document1.count(word) for word in voca_lst]
sent_2_count = [document2.count(word) for word in voca_lst]

In [10]:
# sent_1 = "It is a good practice for us."
# sent_2 = "It was also good to know about it."

df = pd.DataFrame([sent_1_count,sent_2_count],index=[1,2],columns = voca_lst)

In [11]:
df

good  for  about  know  us  .  a  is  it  also  practice  was  to
1     1    1      0     0   1  1  1   1   1     0         1    0   0
2     1    0      1     1   0  1  0   0   2     1         0    1   1

## By using in-built library

In [12]:
from sklearn.feature_extraction.text import CountVectorizer

In [13]:
cvt = CountVectorizer()

In [14]:
x_new = cvt.fit_transform([sent_1,sent_2])

In [15]:
x_new.toarray()

array([[0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0],
       [1, 1, 0, 1, 0, 2, 1, 0, 1, 0, 1]])

In [16]:
cvt.get_feature_names_out()

array(['about', 'also', 'for', 'good', 'is', 'it', 'know', 'practice',
       'to', 'us', 'was'], dtype=object)

In [17]:
df = pd.DataFrame(data=x_new.toarray(), columns=cvt.get_feature_names_out())

In [18]:
df

about  also  for  good  is  it  know  practice  to  us  was
0      0     0    1     1   1   1     0         1   0   1    0
1      1     1    0     1   0   2     1         0   1   0    1

In [19]:
new = "It was good for us."

In [20]:
new_features = cvt.transform([new])

In [21]:
new_features.toarray()

array([[0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1]])

## Bagofword with N-Grams

In [22]:
ngram = CountVectorizer(ngram_range=(1,2))

In [23]:
new_ng = ngram.fit_transform([sent_1,sent_2])

In [24]:
ndf = pd.DataFrame(data=new_ng.toarray(), columns=ngram.get_feature_names_out())

In [25]:
ndf

about  about it  also  also good  for  for us  good  good practice  \
0      0         0     0          0    1       1     1              1   
1      1         1     1          1    0       0     1              0   

   good to  is  ...  it was  know  know about  practice  practice for  to  \
0        0   1  ...       0     0           0         1             1   0   
1        1   0  ...       1     1           1         0             0   1   

   to know  us  was  was also  
0        0   1    0         0  
1        1   0    1         1  

[2 rows x 23 columns]

In [26]:
ngram = CountVectorizer(ngram_range=(2,2))
new_ng = ngram.fit_transform([sent_1,sent_2])
ndf = pd.DataFrame(data=new_ng.toarray(), columns=ngram.get_feature_names_out())
ndf

about it  also good  for us  good practice  good to  is good  it is  \
0         0          0       1              1        0        1      1   
1         1          1       0              0        1        0      0   

   it was  know about  practice for  to know  was also  
0       0           0             1        0         0  
1       1           1             0        1         1

# The TF-IDF Vectorizer

In [27]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [28]:
tfidf = TfidfVectorizer()

In [29]:
x_new = tfidf.fit_transform([sent_1,sent_2])

In [30]:
x_new.toarray()

array([[0.        , 0.        , 0.44665616, 0.31779954, 0.44665616,
        0.31779954, 0.        , 0.44665616, 0.        , 0.44665616,
        0.        ],
       [0.36439074, 0.36439074, 0.        , 0.25926702, 0.        ,
        0.51853403, 0.36439074, 0.        , 0.36439074, 0.        ,
        0.36439074]])

In [31]:
tfdf = pd.DataFrame(data=x_new.toarray(),index=["Sent1","Sent2"], columns=tfidf.get_feature_names_out())
tfdf

about      also       for      good        is        it      know  \
Sent1  0.000000  0.000000  0.446656  0.317800  0.446656  0.317800  0.000000   
Sent2  0.364391  0.364391  0.000000  0.259267  0.000000  0.518534  0.364391   

       practice        to        us       was  
Sent1  0.446656  0.000000  0.446656  0.000000  
Sent2  0.000000  0.364391  0.000000  0.364391